### ISSUE TITLE
Getting "Entity too large" error while rendering multi layer chart

### ISSUE THREAD

**Issue by Eroyi** [tobiashochguertel/helm-editor-frontend#1]
I was trying to render Gitlab Official Helm Chart, editor work just fine, but getting error in rendering.

**Comment by tobiashochguertel** [comment]
[Fixed](https://github.com/tobiashochguertel/helm-editor-template/commit/99a77405cfe16b0993449c52f94b536159f09f64)

Released a new version of the `template` container image https://hub.docker.com/r/tobiashochguertel/th-helm-playground-template/tags

In the case of the following Chart: https://gitlab.com/gitlab-org/charts/gitlab/-/tree/master/charts/gitlab I see then that helm is missing some templates, but that is not related to the editor that is related to the chart.

Works now. Can you give it a try @Eroyi  ?

**Comment by tobiashochguertel** [comment]
[Fixed](https://github.com/tobiashochguertel/helm-editor-template/commit/99a77405cfe16b0993449c52f94b536159f09f64)

Released a new version of the `template` container image https://hub.docker.com/r/tobiashochguertel/th-helm-playground-template/tags

In the case of the following Chart: https://gitlab.com/gitlab-org/charts/gitlab/-/tree/master/charts/gitlab I see then that helm is missing some templates, but that is not related to the editor that is related to the chart.

Works now. Can you give it a try @Eroyi  ?

**Comment by Eroyi** [comment]
Oops sry for the late reply, just got the chance to check my mailbox.
Ive tested the latest version, now im getting a different error 
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>SyntaxError: Bad Unicode escape in JSON at position 2539709<br> &nbsp; &nbsp;at JSON.parse (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at parse (/app/node_modules/body-parser/lib/types/json.js:92:19)<br> &nbsp; &nbsp;at /app/node_modules/body-parser/lib/read.js:128:18<br> &nbsp; &nbsp;at AsyncResource.runInAsyncScope (node:async_hooks:203:9)<br> &nbsp; &nbsp;at invokeCallback (/app/node_modules/raw-body/index.js:238:16)<br> &nbsp; &nbsp;at done (/app/node_modules/raw-body/index.js:227:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/app/node_modules/raw-body/index.js:287:7)<br> &nbsp; &nbsp;at IncomingMessage.emit (node:events:513:28)<br> &nbsp; &nbsp;at endReadableNT (node:internal/streams/readable:1359:12)<br> &nbsp; &nbsp;at process.processTicksAndRejections (node:internal/process/task_queues:82:21)</pre>
</body>
</html>
```

And also the left side could really use a handler to resize the area, it is really hard to navigate.
<img width="412" alt="image" src="https://github.com/tobiashochguertel/helm-editor-frontend/assets/44765750/2879db0a-22f0-4e3a-a3c2-10f09783cdb2">

and abou the charts, ` helm pull gitlab/gitlab --untar `

**Comment by tobiashochguertel** [comment]
I will work on it at the weekend @Eroyi, thanks for providing the feedback about the helm chart.

**Comment by tobiashochguertel** [comment]
@Eroyi Can you provide me your custom configuration for this chart? I don't get this error. I used `helm pull gitlab/gitlab --untar` as chart, and after setting 
![image](https://github.com/tobiashochguertel/helm-editor-frontend/assets/3332669/8c34516b-d92b-4fb5-b4f4-eaa9785b3e4b)

![image](https://github.com/tobiashochguertel/helm-editor-frontend/assets/3332669/13a2b670-e057-48f5-acab-5bf8ac971527)

it renders the chart:

![image](https://github.com/tobiashochguertel/helm-editor-frontend/assets/3332669/6c129e90-f409-4b6c-bd2a-6f3cc8dbabbb)

I need:

- your myValues.yaml (Editor -> Set Configuration Values)
- the selected filename/path

**Comment by tobiashochguertel** [comment]
Add added some handles so that the editor has resizeable Files and Folder Tree. The Editor (Split Editor) has this feature now, too, and also the "My Configuration:" is resizeable. 

But I need more details to find the error which you have @Eroyi. Are you using it on Windows?

**Comment by Eroyi** [comment]
Tried the latest version with fresh pull helm chart, but getting this new error from "Dashboard Template - Bootstrap v5.3"
<img width="308" alt="image" src="https://github.com/tobiashochguertel/helm-editor-frontend/assets/44765750/9bd2728d-f25b-4fd2-90d5-2e59b4bceca5">

Im running with:
Apple M1 Max
* Docker Desktop 4.2.0
  * Engine 20.10.10
  * Compose 1.29.2
* macOS Ventura 13.4
  * Safari 16.5
  * Chrome 114.0 

```
> docker inspect image 64b85c4736bc

............
        "Architecture": "arm64",
        "Os": "linux",
............

**Comment by tobiashochguertel** [comment]
@Eroyi I figured out what the "Oops!..." error caused and fixed it.

There is now a new version at https://hub.docker.com/u/tobiashochguertel

**Comment by Eroyi** [comment]
Tested on 
- WSL on Windows 11 with Ubuntu 22.04.2 LTS
- Podman 3.4.4
- Chrome 115.0.5790.171
- [Bitnami Charts Repo](https://github.com/bitnami/charts)

Two issues was founded:
1.  Getting 
     ```<!-- a padding to disable MSIE and Chrome friendly error page -->``` 
     on browser, and 
     ```
     21#21: *29 client intended to send too large body: 44698916 bytes, client: 10.89.0.1, server: localhost, request: "POST /template HTTP/1.1", host: "localhost:4173", referrer: "http://localhost:4173/"
      ``` 
       in webapp, but can be fix by putting the `client_max_body_size 100M;` in nginx.conf.

2. After I patched the body_size error, getting this in browser instead.
   ```
   {
     "result": {
       "error": {
         "code": 1,
         "killed": false,
         "signal": null,
         "cmd": "helm template ./public/chart -f ./public/myValues.yaml"
       },
       "stderr": "Error: Chart.yaml file is missing\n"
     }
   }
   ```

**Comment by tobiashochguertel** [comment]
Okay, I will check this over the week. Thanks for the help and the Information about the environment.
